version: '3.1'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - db
        networks:
            - red_interna
              
    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9090:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - red_interna
               

    # db 
    db:
        image: mysql
        ports:
            - "3307:3307"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: paraCetamol19
            MYSQL_ROOT_PASSWORD: paraCetamol19
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - red_interna
    #phpmyadmin

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8181:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: paraCetamol19
            MYSQL_ROOT_PASSWORD: paraCetamol19
            UPLOAD_LIMIT: 100M
        networks:
            - red_interna

networks:

    red_interna:
        ipam:
            driver: default
            config:
                - subnet: 192.168.20.0/24

volumes:
    persistent:
